Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.



class Solution {
public:
    char findTheDifference(string s, string t) {
        
        char result = '0';
        int hash1[26] = {0};
        int hash2[26] = {0};
        for(int i = 0; i < s.size(); i++)
            hash1[s[i] - 'a']++;
        for(int j = 0; j < t.size(); j++)
            hash2[t[j] - 'a']++;
        for(int i = 0; i < 26; i++)
        {
            if(hash1[i] != hash2[i])
            {
                result = 'a' + i;
                break;
            }
        }
        return result;
    }
};
